### ISSUE TITLE
《浅谈 TypeScript》1.0.0 版本重写提纲

### ISSUE THREAD

**Issue by icepy** [icepy/typescript-book#3]
- 第一篇 万物起源
  - 第一章 JavaScript 的历史
    - 1.1 黑暗时刻
    - 1.2 标准化
    - 1.3 babel 带来的价值
    - 1.4 未来
  - 第二章 TypeScript 介绍
    - 2.1 什么是 TypeScript
    - 2.2 TypeScript 优势和收益是什么
    - 2.3 未来
  - 第三章 国际惯例 Hello World
- 第二篇 从零开始
  - 第一章 入门基础
    - 1.1 基础类型和变量声明
    - 1.2 函数
    - 1.3 模块
    - 1.4 接口
    - 1.5 类
    - 1.6 泛型
    - 1.7 高级类型
    - 1.8 启用 JSX
    - 1.9 ...
  - 第二章 高阶运用
    - 2.1 泛型在HTTP接口中的运用
    - 2.2 使用类编写一个有趣的动画
    - 2.3 奇技淫巧
    - 2.4 索引类型查询和索引访问
    - 2.5 ...
- 第三篇 优雅实践
  - 第一章 React Component 入门基础
    - 1.1 无状态函数组件
    - 1.2 有状态类组件
    - 1.3 Portals 组件
    - 1.4 Fragments 组件
    - 1.5 PureComponent
    - 1.6 高阶组件
    - 1.7 Hooks
    - 1.8 基础的组件通信机制
    - 1.9 ...
  - 第二章 深度提升
    - 2.1 优雅的使用 Redux
    - 2.2 immutable 优化你的应用性能
    - 2.3 ...

**Comment by baixiaoji** [comment]
期待
